name: Static checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: Linters
        run: |
          pip install pre-commit
          pre-commit run -a
