name: "Train model with different parameters"

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      
      - name: Install model dependencies
        run: pip install -r model/requirements.txt

      - name: Train model with different parameters
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          # silence mlflow deprecation warnings as DagsHub's MLflow
          # doesn't support 'mlflow.search_experiments()' call:
          PYTHONWARNINGS: ignore
        run: |
          export EXPERIMENT_NAME="train-change-params-$(date +"%Y%m%d%H%M%S")"

          for learning_rate in 0.01 0.05 0.1 0.3 0.5; do
              echo learning_rate=$learning_rate
              for max_depth in 5 10 15; do
                  echo max_depth=$max_depth
                  for n_estimators in 5 10 20 50; do
                      echo n_estimators=$n_estimators
                      
                      python model/train.py \
                          --experiment_name=$EXPERIMENT_NAME \
                          --run_name="lr-$learning_rate-md-$max_depth-ne-$n_estimators" \
                          --learning_rate $learning_rate \
                          --max_depth $max_depth \
                          --n_estimators $n_estimators

                  done
              done
          done

