name: "CI/CD with MLflow"

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          # silence mlflow deprecation warnings as DagsHub's MLflow
          # doesn't support 'mlflow.search_experiments()' call:
          PYTHONWARNINGS: ignore
        run: |
          cat train-with-different-params.sh
          chmod +x train-with-different-params.sh
          ./train-with-different-params.sh
